title: H. Kamran
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.hkamran.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC â€” Jan 2
  down: "#ef4444"
  systems:
    - name: Website
      description: My website
      category: Uncategorized
      link: https://hkamran.com/
    - name: Assets
      description: Serves article graphics, creation lists, and more. Reliant on
        Cloudflare and Netlify.
      category: Uncategorized
    - name: Reactor
      category: Discord
      description: A Discord bot to automatically add reactions to specific users' messages
    - name: Brainteasers (client)
      category: Brainteasers
      description: ""
      link: https://brainteasers.hkamran.com/
    - name: Brainteasers (server)
      category: Brainteasers
      description: ""
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#be154d"
  enableLastMod: true
  headerTextColor: white
  logo: https://assets.hkamran.com/images/profile/circular
  incidentPostsPerPage: 5
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#f59e0b"
  notice: "#be154d"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#22c55e"
  categories:
    - name: Uncategorized
      untitled: true
    - name: Discord
      description: ""
      closed: false
    - name: Brainteasers
      description: A trivia game powered by Socket.io and The Trivia API
  description: I continuously monitor the status of my services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: false
  useLargeHeaderDesign: false
